export type AppConfig = {
  host: string;
  port: number;
  projectPhase: "stage_f_pdf_pipeline";
  requestBodyLimitBytes: number;
  keycrmApiBase: string;
  keycrmToken: string;
  keycrmOrderInclude: string[];
  keycrmRequestTimeoutMs: number;
  keycrmRequestRetries: number;
  keycrmRequestRetryBaseMs: number;
  keycrmWebhookSecret: string;
  telegramBotToken: string;
  telegramChatId: string;
  telegramMessageThreadId: string;
  telegramReactionSecretToken: string;
  telegramRequestTimeoutMs: number;
  telegramRequestRetries: number;
  telegramRequestRetryBaseMs: number;
  orderQueueConcurrency: number;
  orderQueueMaxSize: number;
  reactionQueueConcurrency: number;
  reactionQueueMaxSize: number;
  queueJobTimeoutMs: number;
  idempotencyStorePath: string;
  productCodeRulesPath: string;
  reactionStatusRulesPath: string;
  telegramMessageMapPath: string;
  telegramLegacyClientPath: string;
  qrRulesPath: string;
  outputDir: string;
  fontPath: string;
  emojiFontPath: string;
  emojiRenderMode: "font" | "apple_image";
  appleEmojiBaseUrl: string;
  appleEmojiAssetsDir: string;
  pdfLegacyModulePath: string;
  pdfColorSpace: "RGB" | "CMYK";
  pdfStickerSizeMm: number;
  pdfOffWhiteHex: string;
  pdfRasterizeDpi: number;
  qrA5RightMm: number;
  qrA5BottomMm: number;
  qrA5SizeMm: number;
  qrA4RightMm: number;
  qrA4BottomMm: number;
  qrA4SizeMm: number;
};
